# This is a basic workflow to help you get started with Actions

name: Artifact

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

 
jobs:
  runs-on: ubuntu-latest
    example-job:
      name: Save output
      steps:
        - shell: bash
          run: |
            expr 1 + 1 > output.log
        - name: Upload output file
          uses: actions/upload-artifact@v2
          with:
            name: output-log-file
            path: output.log
    
