# This is a basic workflow to help you get started with Actions

name: Test
env:
  DAY_OF_WEEK: Monday
  
# Controls when the workflow will run
on: 
  push:
    branches: 
      - master
    
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        if: ${{ env.DAY_OF_WEEK == 'Monday' }}
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        run: format('Hello {0} {1} {2}', 'Mona', 'the', 'Octocat')
        env:
          First_Name: Mona
